### PR TITLE
Only allow absolute URLs for shortening

### LINKED ISSUE #14: Only allow absolute URLs for shortening.
If the `originalUrl` does not include the scheme, the URL will be interpreted as a relative URL and be appended to the Shortener service's host when resolved.
#### New URL POST body:
```json
{
  "orginalUrl":"stackoverflow.com/questions/49136669"
}
```

#### Resolved URL
```shell
$ curl -i  https://ospk.org/abc123def

HTTP/2 308
content-type: text/html; charset=utf-8
location: /stackoverflow.com/questions/49136669
```

I think we should just return an error if the `originalUrl` does not include the scheme.

### PR DESCRIPTION
**Pull request by harveysanders**
Resolves #14 
Do not allow relative URLs when creating short links.

### CODE REVIEW

**Comment by ptbarnum4** [comment]
@harveysanders should the shortener reject the url or resolve the `https://` if it doesn't exist? I feel like this wouldn't cause any side effects or ambiguity, assuming we wouldn't expect other protocols. I do see the benefit of doing it this way and leaving it up to the requester to handle ensuring the protocol exists on the url. 

something like this
```go
func ResolveHTTP (url string) string {
    if strings.HasPrefix(url, "http") {
        return url
    }
    return fmt.Sprintf("https://%s", url)
}
```

forgive the syntax.. I wrote it in the github comment box. It might be off

**Comment by harveysanders** [comment]
@ptbarnum4 if i understand you correctly, this snippet only handles URLs that are prefixed with `http`.  I think switching http to https is another problem entirely.  I would say Https upgrades are responsibility of the domain servicing the request, not the URL shortener service. Most have systems in place to automatically do this. For example, if you hit http://github.com, GitHub will redirect to https://github.com. 

The problem this PR is getting to solve is if someone creates a short link with a relative URL, with no protocol at all, this service will resolve it as a URL relative to the short link service domain, ospk.org.

From the example on the [issue](https://github.com/OperationSpark/service-shorty/issues/14#issue-1448630102), the result would be

```
https://ospk.org/stackoverflow.com/...
```

Anyway i think the API should be pretty strict with what's acceptable, report errors and leave it up the the frontend client(s) to decide what to do. 

What ya think?

**Comment by ptbarnum4** [comment]
@harveysanders that snippet would prepend `https://` to the url if it doesn't start with `http` or `https`. if it does start with `http` or `https` the url would just pass through unchanged, allowing the sender to specify, but assuming `https` otherwise. I think the only way it could break is if a domain starts with `http` where the protocol was not specified (seems like a very rare edge case). 

I see now that `ResolveHTTP` might have been a poor name, it would maybe be better named `CheckOrAddProtocol` which could be called with the `originalUrl`, not the incoming url to be resolved.

the link in the issue would resolve to 
```
https://stackoverflow.com/questions/49136669
```

I think either way works. it was a consideration for when the ui is built and where would the responsibility lie in making sure the protocol is included

**Review by ptbarnum4 — APPROVED** [review]

**Comment by harveysanders** [comment]
Ah i got ya. I thought i was misreading it. Sorry about that. 
While, yeah, i think > 90% of links will be for https, some sites still don't use SSL this could break those links if the protocol was omitted. I think it would also break deep links that use a custom scheme. 

But yeah most of the time this would probably work fine. I guess I'm generally not a fan making assumptions when the input is not what's expected, at least on the service side. I think this type of assistance would be better suited on the client side

**Pull request merged**
